default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: 'niufoods'
  password: 'niufoods123'

development:
  <<: *default
  database: dev-bd

test:
  <<: *default
  database: dev-test

production:
  <<: *default
  database: dev-prod
