:scheduler:
  :schedule:
    forty_seconds_report_data:
      cron: '*/40 * * * * *'
      class: FortySecondsReportDataWorker

    update_device_status:
      cron: '*/30 * * * * *'
      class: DeviceStatusUpdateWorker
